### ISSUE TITLE
Blocks using Fluidlogged API don't show water

### ISSUE THREAD

**Issue by ralseilii** [Asek3/sodium-1.12#6]
### Bug Description

Some water-containing blocks in certain mods cannot contain water, such as oceanic expanse mod seagrass and most of the marine plants in prehistoric nature mod, even cannot contain water when adding the Fluidlogged-API mod.

### Reproduction Steps

open game with oceanic expanse mod and vintagium, then find ocean

### Log File

no log

**Comment by ralseilii** [comment]
by the way, when installing it alongside CensoredASM, enabling 'onDemandAnimatedTextures=true' in CensoredASM's config will result in the loss of all dynamic textures, such as fire and flowing water.

**Comment by jbredwards** [comment]
The fluidlogged api issue is something that needs to be fixed from both mods' ends. When I release the next update for that mod (or when the source code is on github), I'll start working on a PR to vintagium for compatibility

**Comment by embeddedt** [comment]
> by the way, when installing it alongside CensoredASM, enabling 'onDemandAnimatedTextures=true' in CensoredASM's config will result in the loss of all dynamic textures

This is fixed now

**Comment by ralseilii** [comment]
> The fluidlogged api issue is something that needs to be fixed from both mods' ends. When I release the next update for that mod (or when the source code is on github), I'll start working on a PR to vintagium for compatibility

thank you really hoping for it

**Comment by ralseilii** [comment]
well will it be fixed

**Comment by jbredwards** [comment]
> well will it be fixed

Yes:
> The fluidlogged api issue is something that needs to be fixed from both mods' ends. When I release the next update for that mod (or when the source code is on github), I'll start working on a PR to vintagium for compatibility

The next update for fluidlogged api is mostly done, it's just in the polishing/bug fixing stage now

**Comment by LuizLoyola** [comment]
Did this update release? Tested with Fluidlogged API v2.2.7, Vintagium v0.1 (Build 78) and Oceanic Expanse v1.1.2, problem still there.

**Comment by LuizLoyola** [comment]
Just tested with Biomes O' Plenty, and their "waterlogged" blocks are also bugged, so it doesn't look like a Fluidlogged API bug. Is Vintagium/Sodium 1.12 still in development? Last actual commit was 6 months ago...

**Comment by KuroNeko87** [comment]
![2024-07-28_01 43 14](https://github.com/user-attachments/assets/c6b86ebc-fca7-48a5-b8b3-af3d468ada4e)
![2024-07-28_01 43 54](https://github.com/user-attachments/assets/f489e516-9272-4a68-b823-3de017163dd3)

Yep, still there. Be using Opticrap for now until (hopefully) this gets fixed.
